title: Prince's scribbles
description: My repository of some things that I've been thinking about.
author: Prince Okoli
baseurl: "" # the subpath of your site, e.g. /blog
url: princyok.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  princyok
linkedin_username: princeokoli

scholar:
  style: ieee

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-scholar
markdown: kramdown

permalink: none

defaults:
  -
    scope:
      path: "assets/images"
    values:
        image: true
